### ISSUE TITLE
Question about server setup and talking to github

### ISSUE THREAD

**Issue by j-panasiuk** [young/fsfev2#1]
Hi Jem!

First of all thanks for the fantastic course! I've been doing frontend work for a few years now, but still any time something server-sided comes up, I feel like that ["I have no idea what I'm doing"](https://miro.medium.com/max/455/1*snTXFElFuQLSFDnvZKJ6IA.png) dog.
This course really helps so much in demystifying all the things! :)

Now, onto the actual question...

In the section **Server Setup** / **Version Control with git** we do the following steps:
1) (github) Create git repository
2) (server) Create ssh key pair (id_rsa). This is supposedly needed to communicate with github without being prompted for username/password every time
3) (github) Add newly created public key (id_rsa.pub) as a new github key in settings
4) (server) Clone repository over ssh, add github as a remote etc.

What I don't understand is why do we need to go through this process, instead of just cloning/pulling code from github repo over HTTPS? As in:
1) (github) Create git repository
2) (server) Clone repository over https, pull fresh changes over https etc.

An obvious difference is that in the second case we can't *push* changes to github, but is that even something that we want to allow? Developing and pushing the will be done from local machine anyway, right?

Also in the case where a malicious person gets into the server, can't they use the generated keys to get full access to github repository too? If we just anynomusly pull code over https this is not an issue.

I'm sure there is some important use case that I'm not aware of, but this is bugging me quite a bit :)

**Comment by j-panasiuk** [comment]
After I wrote all of that, it occurred to me that I've been using a public git repository for now, but in a real world scenario it would likely be a private one. So setting up access over ssh obviously makes sense in that case.

So I answered my own question, I guess.

**Comment by young** [comment]
Haha yes we're building more for the "real world" application case of a private repo. If we were building a production server with a private repo, I'd use [deploy keys](https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys) which are read only but in a course with this much content, I have to pick and choose what I cover 😄. That said, it's great you're thinking about server security and the implications of someone getting their hands on a private key. Way to think fullstack!
