### ISSUE TITLE
Nginx not serving changed files

### ISSUE THREAD

**Issue by NickWoodward** [young/fsfev2#2]
I've changed the content of my app.js file to `res.send('A new message')`, but when I navigate to my IP address I'm met with the old content.

I've used incognito mode and forced a refresh, so I don't think it's being cached on the client side. I've read that I can delete the cache on the server - but I don't have the folder var/cache/nginx

Has anyone come across similar?

Thanks

**Comment by NickWoodward** [comment]
It seems to update the file if I turn the server off and then back on in the Digital Ocean dash, but not if I run 'sudo service nginx restart'

**Comment by young** [comment]
@NickWoodward NodeJS loads the files into memory on startup so when you alter a file, you generally have to reload the NodeJS application to see your changes.

**Comment by NickWoodward** [comment]
ah ok - I did think about how we were running node on the server without a nodemon or watch like option. i guess i should just continue to develop locally and then pull from github?

ps as a man "forced" to shave for money by gillette - I assume that trophy is for your beard?

**Comment by NickWoodward** [comment]
> 
> 
> @NickWoodward NodeJS loads the files into memory on startup so when you alter a file, you generally have to reload the NodeJS application to see your changes.

Ah yes, sorry it all being on a server confused me, but you can still just use the watch flag like you would locally!

Thanks

**Comment by young** [comment]
@NickWoodward Absolutely. Maybe for V3 I'll throw in something about Nodemon but I didn't want to throw too many tools at people since we have a ton of topics to cover 😄.

Good luck with your project!

**Comment by NickWoodward** [comment]
Thanks, really enjoying the course!
